//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Smoke.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parent_id { get; set; }
        public string abbreviation { get; set; }
        public string area_code { get; set; }
        public string post_code { get; set; }
        public string id_code { get; set; }
        public string car_code { get; set; }
        public byte level_id { get; set; }
    }
}
