//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Smoke.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mobile_no { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public int department_id { get; set; }
        public int shop_id { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birth_day { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string note { get; set; }
        public byte status { get; set; }
        public int create_by { get; set; }
        public System.DateTime create_date { get; set; }
        public int update_by { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
