//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Smoke.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public string name { get; set; }
        public string icon_class { get; set; }
        public string action_url { get; set; }
        public string menu_no { get; set; }
        public System.DateTime create_date { get; set; }
        public int create_by { get; set; }
        public System.DateTime update_date { get; set; }
        public int update_by { get; set; }

        public Menu[] children { get; set; }
    }
}
